version: '3'

services:
  # server:
  #   env_file:
  #     - ../.env
  #   build:
  #     context: .
  #     dockerfile: server.dockerfile
  #   volumes:
  #     - ..:/workspaces:delegated
  #   command: sleep infinity
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  # client:
  #   build:
  #     context: .
  #     dockerfile: client.dockerfile
  #   volumes:
  #     - ..:/workspaces:delegated
  #   command: sleep infinity
  #   ports:
  #     - 8080:3000
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:delegated
    command: sleep infinity
    ports:
      - "3000:3000" # Rails
      - "3001:3001" # Next.js
  db:
    image: mysql:8.0
    env_file:
      - ../.env
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  db-store: